### PR TITLE
Empty Baseline/Cost failed

### PR DESCRIPTION
**Pull request by LordHelmchen**
Hi Jon,
I finally upgraded mpxj in my repository.
My company has a decent throughput with different XMLs from MS Project. It happens somtimes that I get slightly malformed files from other companies. This enables one situation with empty tags.

### CODE REVIEW

**Comment by joniles** [comment]
I've added the `DatatypeConverter` changes to MPXJ, thanks for that! Not sure about the changes to `TaskContainer` can you demo the problem that it solves?

**Comment by LordHelmchen** [comment]
I ususally build the Task structure based on the structure of the application i get it from. I export from ACOS to MS Project for example. In order for MSP to correctly read the file the IDs need to be ordered thats what synchronizeTaskIDTohierarchy is for (you know that). But when I called it after integrating your changes the clear() removed all attached data like ResourceAssignments and child Tasks. The goal was to update the IDs from the structure but it destroyed the structure.

**Comment by LordHelmchen** [comment]
Since Outline Codes have to be collected in Project.OutlineCodes in a MSPDI file, I added generation of the respective lookup table to the MSPDIWriter.

**Comment by joniles** [comment]
Hi, I will look at the outline code changes soon. I have updated the implementation of `synchronizeTaskIDTohierarchy` to be non-destructive, could you see if that works for you without your changes to `TaskContainer`?

**Comment by joniles** [comment]
Hi, I've had a look at this. Unfortunately as we're not correctly handling hierarchical outline code values presently, for me this change compounds the problem by introducing new lookup table entries where we should be breaking down the outline code and walking through the lookup table to find the existing entry. For example if we have a hierarchical outline code `ABC.123` there will already be two entries in the lookup table, one for `ABC` (the parent) and one for `123` (the child). The correct thing for us to do would be to locate the child code in the lookup table and use the ID value for that. Instead we end up inserting a new entry for `ABC.123` and generating a new ID value for that.

This whole area is on my to-do list of things to work on so we can make this functionality work correctly. Sorry I can't take the outline code change on at  the moment, but I hope the other change I made to MPXJ in `synchronizeTaskIDTohierarchy` will allow you to remove your changes in `TaskContainer` now.

**Comment by LordHelmchen** [comment]
The change to synchronizeTaskIDTohierarchy solves my problem with it and I can remove my changes there.

If I understand you correctly my code is breaking MSPDI when there are hierarchical code masks defined on an outline code, right?
But it should work for outline codes without masks and a defined seperator/hierachical structure.

However I am unsure wether collecting the possible values in the actual Project file would be preferable to the MSPDIWriter, where it feels a bit like a hack anyway. But I don't know your plan for the Project file if it is meant to be a general abstract representation or tied to MS Project.

**Pull request closed without merging**
