### PR TITLE
Issue #323 : Return Activity Codes in Phoenix readers

### PR DESCRIPTION
**Pull request by cjohnspm**

### CODE REVIEW

**Comment by joniles** [comment]
Many thanks for this. I've taken the liberty of attributing the change to you @cjohnspm, let me know if you'd prefer different.

For the moment I've updated the flag so that the current behaviour when reading Phoenix schedules remains unchanged. We can consider if we should switch the default behaviour for v11.0.0 as it could be seen as a breaking change!

In the meantime, I'll be looking at adding a mechanism to allow flags like the one we've just introduced in this PR to be passed from the `UniversalProjectReader` to the specific reader class used when reading a schedule. This should avoid the need for users to manage the individual reader classes themselves, they can just use `UniversalProjectReader`, set their preferences there, and let it deal with which reader class to use and how it is configured.

**Comment by cjohnspm** [comment]
Thanks @joniles!  Appreciate the quick turnaround.

**Comment by joniles** [comment]
As noted above, if you are using `UniversalProjectReader`, I've added a mechanism to allow properties to be set in the underlying reader classes: https://github.com/joniles/mpxj/pull/357

**Comment by cjohnspm** [comment]
Awesome, works as intended.  Thanks much! Looking forward to the release.

**Comment by joniles** [comment]
@cjohnspm thanks for the contribution! MPXJ 10.10.0 is available now with these changes.

**Pull request merged**
