### PR TITLE
German Project Versions write decimal values with "," as decimal point ..

### PR DESCRIPTION
**Pull request by LordHelmchen**
into the Extended Attributes.

They can read both decimal points. To be able to read MSPDI files from German Project versions, the DatatypeConverter can read both decimal points aswell.

### CODE REVIEW

**Comment by joniles** [comment]
Thanks for this. I took a slightly different approach to try to make the comparison and replacement operations as efficient as possible, hence I haven't directly merged this pull request.

**Comment by LordHelmchen** [comment]
I'll synchronize my fork/working copy with the base again, for when I encounter anything else.

**Comment by LordHelmchen** [comment]
What do you think of the Outline Codes for MSPDI? The resulting Syntax is correct, but a recent MSP update made it crash when a MSPI file contains any Outline Codes, even when written by MSP itself.

**Comment by joniles** [comment]
I'd like to finish the support for outline codes, but if I remember correctly it's actually a much bigger piece of work to finish it for MPP files and MSPDI files. I'll take a look again when I have more time to spend with it.

Which version of MS Project crashes with MSPDI files containing outline codes?

**Comment by LordHelmchen** [comment]
Project 2013 and, IIRC even 2007.

**Pull request closed without merging**
