### PR TITLE
Issue #323: Adding support for activity codes for Phoenix files

### PR DESCRIPTION
**Pull request by rsinha9**

### CODE REVIEW

**Comment by joniles** [comment]
@rsinha9 apologies, it was a public holiday here yesterday... I'm still catching up! I'm aiming to provide feedback today.

**Comment by joniles** [comment]
To move this forward: my preference for now as we're not adding new attributes with this change would be to leave the initialisation via the constructor as it is in the current `master` version of the code, and just implement the functionality necessary to populate the activity codes from Phoenix schedules. If we get to the point where we need to add more attributes, then I'd suggest that we'd create two new PRs, one to switch to using the builder pattern for these classes, then once that's in, add the new attribute.

**Comment by rsinha9** [comment]
Sounds good @joniles, I see a few different ways that we can implement it with constructor based initialization for those fields.

1) We could have the addActivityCode function on ProjectFile take in all of those attributes and construct the instance and either pass the ProjectFile so that the ActivityCode object can get it's uniqueId from the counter.
2) We could have the addActivityCode function take in an ActivityCode object that is constructed in the Reader and then either set the ID based on the counter or clone it while setting the ID, so that we maintain immutability.
3) We could in theory have the PhoenixReader ask the ProjectFile for the next unique ID when building the object, but this to me is completely different than other parts of the project.

**Comment by joniles** [comment]
To keep things simple for this change, I'd prefer to accept the Unique ID as an argument, and allow the Phoenix reader code to generate this, at least for now.

> We could in theory have the PhoenixReader ask the ProjectFile for the next unique ID when building the object, but this to me is completely different than other parts of the project.

I appreciate what you're saying here. We already have a mix of approaches with both mutable and immutable classes making up various parts of the MPXJ data model. The way we do unique ID generation for `Task`, `Resource` etc I think makes more sense for the mutable class approach where we aren't expecting to have the full set of attributes available at the point we create an instance of a class.

To move forward, I'd suggest using a simple counter in the Phoenix reader classes to allow us to generate Unique ID values and instantiate the classes without having to add any new infrastructure around this. This will get us to the point where the code does what you need. We can then take a broader view around mutable vs. immutable classes and what we'd need to do to make this consistent across MPXJ.

**Comment by cjohnspm** [comment]
This PR can be closed.  A new PR has been opened for these changes

**Pull request closed without merging**
