### PR TITLE
Improvement for performance when reading files

### PR DESCRIPTION
**Pull request by tiagodemello**
It was a small change in the DateHelper changing the Calendar for the new lib JodaTime with do not use machine resources that is used for new Calendar instances.
In manual tests a reading operation with a huge file that used to takes 10 minutes started to take 30 seconds after the change.
The change was done only in the most used method that was responsable for the most of waiting time.

### CODE REVIEW

**Comment by joniles** [comment]
Do you have a sample file I can benchmark with? Thanks!

Jon

**Comment by tiagodemello** [comment]
> Do you have a sample file I can benchmark with? Thanks!
> 
> Jon

Sure, here is a link: https://drive.google.com/open?id=1Nh42cfbc62mxA-K72UAVV2spHxXpv_x1

**Comment by lucasventurasc** [comment]
That improvement will help my team a lot.

**Comment by joniles** [comment]
Thanks for submitting this pull request, it was certainly thought provoking. For a long time now I've wanted to overhaul the way MPXJ works with date and time values. Originally I was looking at Joda, but my understanding is that from Java 1.8 the new date and time classes provided as part of the JRE are actually based on Joda, so it would be more useful to use those.

As it happens the latest version of one of MPXJ main dependencies (Apache POI) now only supports Java 1.8, so it's getting close to the time I will stop supporting older Java versions... which means I can take advantage of the new date and time classes.

Your pull request also made me think more deeply about the way I was working the the `Calendar` class. For many other classes which are expensive to instantiate I'd provided optimisations, and I'm surprised that I hadn't tackled this already.

On that basis, what I thought I would do was benchmark the current performance using the `master` branch, the changes from your pull request, and also a branch I've just created which avoids creating new `Calendar` instances. I used the `MpxjConvert` utility from the distribution to time how long it takes to read the sample MPP file you provided (the utility writes this time to the console when it runs). I also ran the tests with three different JVM versions to see what effect that had, and three runs for each JVM/branch combination.

Here are the results:

| Branch                | Java           | Run 1 | Run 2 | Run 3 | Average | Change  |
|-----------------------|----------------|-------|-------|-------|---------|---------|
| master                | Java 1.6.0-45  | 41383 | 40896 | 41105 | 41128   |         |
|                       | Java 1.7.0-71  | 35656 | 34938 | 34954 | 35183   |         |
|                       | Java 1.8.0-131 | 37687 | 38141 | 38313 | 38047   |         |
|                       | Java 10.0.1    | 17970 | 17375 | 17470 | 17605   |         |
|                       |                |       |       |       |         |         |
| tiagodemello          | Java 1.6.0-45  | 47875 | 47859 | 47046 | 47593   | 15.72%  |
|                       | Java 1.7.0-71  | 40391 | 41062 | 40453 | 40635   | 15.50%  |
|                       | Java 1.8.0-131 | 41610 | 42141 | 42484 | 42078   | 10.60%  |
|                       | Java 10.0.1    | 18032 | 18297 | 18172 | 18167   | 3.19%   |
|                       |                |       |       |       |         |         |
| calendar-optimisation | Java 1.6.0-45  | 30734 | 30906 | 30391 | 30677   | -25.41% |
|                       | Java 1.7.0-71  | 26906 | 27140 | 26656 | 26901   | -23.54% |
|                       | Java 1.8.0-131 | 27330 | 27095 | 26970 | 27132   | -28.69% |
|                       | Java 10.0.1    | 14000 | 14485 | 13641 | 14042   | -20.24% |

The `Change` column represents the change relative to the baseline (in this case the master branch), where a negative value means the performance improved. Unfortunately it looks like this branch is slower than the baseline when benchmarked using the provided file, however the good news is that it looks like the changes I made do provide a performance improvement so I'm hoping you will find those beneficial.

Would you be able to try the branch I've created to confirm that it improves performance for you? Also it would be interesting to understand which version of Java you were using to test your changes, or if you were benchmarking the .Net version?

**Comment by joniles** [comment]
Hi, I've merged my changes into master, so you'll be able to test from that.

On a related note, you mention that you are using Java 1.6... if I were to update MPXJ to require Java 1.8, would that cause you an issue? Just trying to understand how widespread use of older Java versions is. Thanks!

**Comment by lucasventurasc** [comment]
Hi @joniles I and @tiagodemello we are from the same team, I can answer you.

Our product is running Java 1.8 at runtime but we can't compile anything in Java 1.8 because we have many customers with their own data center (our product is a web application) and we don't have control of their java version. So right now would be impossible for us to compile using Java 1.8 features.

So our code must be compatible with Java 1.6 and Java 1.7 and for that, we can't use any feature introduced after JDK 1.6.

But to be honest with you we don't update our MPXJ library very often, probably we will just update again for be compatible with new MS Project versions and we do this at least with 1 year of delay.

Something very important to us is that we have a hundred application servers using the same JVM, which means that any JVM resource will be a neck, for example, the Java Calendar.

We already tried the Joda Time Library in other cases and it solved many performance issues. We are talking about 500% improvement in performance in that kind of environment. The performance increased in just one application server is not too representative.

We tested the master branch and the performance improvement was almost the same as using the Joda Time Library (in our machines with just one application server), your new optimizations are using JVM resources?

Thank you for help!!!

We really appreciated it.

**Comment by tiagodemello** [comment]
I'm closing the pull request for the comments above. 
Thank's =]

**Pull request closed without merging**
