### PR TITLE
Store Calendar ID and Base Calendar ID

### PR DESCRIPTION
**Pull request by forenpm**
Another diff from my fork from a while ago.
I had need of getting the P6 clndr_id and base_clndr_id from XER.

### CODE REVIEW

**Comment by joniles** [comment]
Thanks for this. I ended up taking a different approach, just using the calendar IDs direction, to `ProjectCalendar.getUniqueID()` will report the ID retrieved from the XER file or the P6 database. I've just merged the code to do this.

**Comment by forenpm** [comment]
Thank you!
What do you think about base_clndr_id?

I have found instances where base_clndr_id differs from the default project calendar.
It is rare, but it does exist.  The reason I need them is because the calendar and base calendar exceptions must be combined to get the final/full exceptions result.

**Comment by forenpm** [comment]
Here is an example from an XER I have:

| clndr_id | default_flag | base_clndr_id |
| --- | --- |
| 592 | N |  |
| 597 | Y |  |
| 740 | N |  |
| 788 | N | 740 |
| 789 | N | 740 |
| 790 | N | 597 |
| 791 | N | 597 |

**Comment by joniles** [comment]
Apologies, I thought I'd already dealt with that. I've just merged changes which should give you the functionality you need. The hierarchy of calendars from a P6 schedule is preserved in MPXJ. From a given calendar you can call `getParent()` to work your way up through the hierarchy. As usual the calculations performed on a calendar will take into account the parent calendar, for example determining a working day on a derived calendar will take into account exceptions defined in the parent calendar.

**Comment by forenpm** [comment]
Thank you very much Jon!
I will give this a shot and can start taking Nuget builds again :)

Cheers!

**Pull request closed without merging**
